### ISSUE TITLE
Build failed after installation

### ISSUE THREAD

**Issue by aj-anuragjain** [Jobeso/react-native-whatsapp-stickers#26]
## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
      Memory: 24.54 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
build fails after installation and linking

## Reproducible Steps
`react-native link react-native-whatsapp-stickers`

## Error log
`error Command failed: ./gradlew app:installDebug
debug Error: Command failed: ./gradlew app:installDebug
    at checkExecSyncError (child_process.js:607:13)
    at execFileSync (child_process.js:627:13)
    at runOnAllDevices (/Users/jainhub/Documents/anarReactNative/node_modules/@react-native-community/cli/build/commands/runAndroid/runOnAllDevices.js:58:39)
    at buildAndRun (/Users/jainhub/Documents/anarReactNative/node_modules/@react-native-community/cli/build/commands/runAndroid/runAndroid.js:142:41)
    at then.result (/Users/jainhub/Documents/anarReactNative/node_modules/@react-native-community/cli/build/commands/runAndroid/runAndroid.js:104:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)`

**Comment by Jobeso** [comment]
v2.0.0 was just released which adds RN 0.60 support. Please reopen the issue if your problem still persists.
