### ISSUE TITLE
Unable to get provider com.jobeso.RNWhatsAppStickers.StickerContentProvider

### ISSUE THREAD

**Issue by Haseeba393** [Jobeso/react-native-whatsapp-stickers#61]
## Environment
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 36.40 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Describtion
I have followed the steps as given here [https://github.com/Jobeso/react-native-whatsapp-stickers](url). I also changed my android project midSdkVersion to 19 as this package has minSdkVersion is 19. Now, it is building successfully using android studio but the app is crashing.

## Logcat
2021-04-14 15:07:59.937 12677-12677/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wastickers, PID: 12677
    java.lang.RuntimeException: Unable to get provider com.jobeso.RNWhatsAppStickers.StickerContentProvider: java.lang.RuntimeException: contents.json file has some issues: contents.json
        at android.app.ActivityThread.installProvider(ActivityThread.java:7237)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6721)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6618)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.RuntimeException: contents.json file has some issues: contents.json
        at com.jobeso.RNWhatsAppStickers.StickerContentProvider.readContentFile(StickerContentProvider.java:149)
        at com.jobeso.RNWhatsAppStickers.StickerContentProvider.getStickerPackList(StickerContentProvider.java:155)
        at com.jobeso.RNWhatsAppStickers.StickerContentProvider.onCreate(StickerContentProvider.java:90)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1920)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7234)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6721) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6618) 
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7555) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963) 
     Caused by: java.io.FileNotFoundException: contents.json
        at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:701)
        at android.content.res.AssetManager.open(AssetManager.java:675)
        at com.jobeso.RNWhatsAppStickers.StickerContentProvider.readContentFile(StickerContentProvider.java:146)
        at com.jobeso.RNWhatsAppStickers.StickerContentProvider.getStickerPackList(StickerContentProvider.java:155) 
        at com.jobeso.RNWhatsAppStickers.StickerContentProvider.onCreate(StickerContentProvider.java:90) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1920) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7234) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6721) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6618) 
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7555) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963) 
2021-04-14 15:07:59.976 12677-12677/? I/Process: Sending signal. PID: 12677 SIG: 9

**Comment by Jobeso** [comment]
It looks like something with the content.json is wrongly configured. Maybe a file missing or a name is wrong. Also it's important that the files have the correct format (webp etc.).

```
java.lang.RuntimeException: contents.json file has some issues: contents.json
```

**Comment by Haseeba393** [comment]
yes, i have followed the exact documentation but nothing is happening
