### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by pavankommi** [Jobeso/react-native-whatsapp-stickers#86]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\path\node_modules\react-native-whatsapp-stickers\android\build.gradle' line: 34

* What went wrong:
A problem occurred evaluating project ':react-native-whatsapp-stickers'.
> Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

    at makeError (path\node_modules\execa\index.js:174:9)
    at path\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (path\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:142:9)

**Comment by Idan-Maimon1** [comment]
Have you managed to fix it?

**Comment by Jobeso** [comment]
Might be related to #78, please check the solution there and update here if it resolved your issue.

**Comment by Aleksefo** [comment]
Here's the fix:
https://stackoverflow.com/a/72951366/8697675

You need to replace compile with implementation

**Comment by Aleksefo** [comment]
Here's the fix PR: https://github.com/Jobeso/react-native-whatsapp-stickers/pull/89

**Comment by Jobeso** [comment]
@Aleksefo Thanks for fixing it. Released v2.0.3 with your fix.
